export const staticPackages = [
  {
    value: 43,
    label: "Free",
    price: 0,
    description: "Basic features for local visibility",
    no_media: 5,
    visibility: "district / city",
    features: [
      { text: "5 Mega/ or equal No.of photos", enabled: true },
      { text: "Visibility district / city", enabled: true },
      { text: "Position in Search", enabled: false },
      { text: "Access to Supplier", enabled: false },
      { text: "Adds. in our Social Media", enabled: false },
      { text: "Account management option", enabled: false },
    ],
  },
  {
    value: 2,
    label: "Silver",
    price: 10,
    description: "Enhanced features for city/country reach",
    no_media: 20,
    visibility: "city / country",
    no_invitation: 5,
    features: [
      { text: "20 Mega", enabled: true },
      { text: "Visibility city / country", enabled: true },
      { text: "5 Max.no of received invitations (Monthly)", enabled: true },
      { text: "Access to suppliers (City/country)", enabled: true },
      { text: "Position in Search", enabled: false },
      { text: "Adds. in our Social Media", enabled: false },
      { text: "Account management option", enabled: false },
    ],
  },
  {
    value: 3,
    label: "Gold",
    price: 30,
    description: "Advanced features with priority positioning",
    no_media: 50,
    visibility: "All",
    no_invitation: 10,
    features: [
      { text: "50 Mega", enabled: true },
      { text: "Visibility (All)", enabled: true },
      { text: "10 Max.no of received invitations (Monthly)", enabled: true },
      { text: "Access to suppliers (City/country)", enabled: true },
      { text: "Position in Search (First in city)", enabled: true },
      { text: "Adds. in our Social Media (1/on all)", enabled: true },
      { text: "Account management option (With Fee)", enabled: true },
    ],
  },
  {
    value: 4,
    label: "Platinum",
    price: 50,
    description: "Premium features with global reach",
    no_media: 100,
    visibility: "All",
    no_invitation: 20,
    features: [
      { text: "100 Mega", enabled: true },
      { text: "Visibility (All)", enabled: true },
      { text: "20 Max.no of received invitations (Monthly)", enabled: true },
      { text: "Access to suppliers (Global)", enabled: true },
      { text: "Position in Search (First at your country)", enabled: true },
      { text: "Adds. in our Social Media (3/all)", enabled: true },
      { text: "Account management option (With Fee)", enabled: true },
    ],
  },
  {
    value: 5,
    label: "Premium",
    price: 100,
    description: "Ultimate package with unlimited features",
    no_media: -1,
    visibility: "All",
    no_invitation: -1,
    features: [
      { text: "Unlimited Storage", enabled: true },
      { text: "Visibility (All)", enabled: true },
      { text: "Unlimited Max.no of received invitations", enabled: true },
      { text: "Access to suppliers (Global)", enabled: true },
      { text: "Position in Search (First of all)", enabled: true },
      { text: "Adds. in our Social Media (unlimited)", enabled: true },
      { text: "Account management option (Free)", enabled: true },
    ],
  },
];
